# Generated by Django 4.2.23 on 2025-07-10 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Asignatura')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10, verbose_name='Día')),
                ('hora', models.CharField(choices=[('1ª', '08:30 - 09:25'), ('2ª', '09:25 - 10:20'), ('3ª', '10:20 - 11:15'), ('4ª', '11:45 - 12:40'), ('5ª', '12:40 - 13:35'), ('6ª', '13:35 - 14:30'), ('7ª', '16:00 - 16:55'), ('8ª', '16:55 - 17:50'), ('9ª', '17:50 - 18:45'), ('10ª', '19:00 - 19:55'), ('11ª', '19:55 - 20:50'), ('12ª', '20:50 - 21:45')], max_length=5, verbose_name='Hora')),
                ('asignatura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.asignatura', verbose_name='Asignatura')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Franja Horaria',
                'verbose_name_plural': 'Franjas Horarias',
                'unique_together': {('profesor', 'dia', 'hora')},
            },
        ),
    ]
