# Generated by Django 4.2.23 on 2025-07-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_asignatura_alter_customuser_managers_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='dias_asuntos_propios',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de Asuntos Propios Asignados'),
        ),
    ]
