# Generated by Django 4.2.23 on 2025-08-02 11:35

from django.db import migrations, models
import django.db.models.deletion
import documento.models.documento


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Documento',
                'verbose_name_plural': 'Categorías de Documentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Solicitud de permiso por visita médica', max_length=200, verbose_name='Nombre de la Plantilla')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Slug (URL amigable)')),
                ('descripcion', models.TextField(blank=True, help_text='Breve explicación sobre el uso de la plantilla.', verbose_name='Descripción')),
                ('archivo', models.FileField(help_text='Sube el documento (.docx, .pdf, .odt, etc.)', upload_to=documento.models.documento.ruta_plantilla, verbose_name='Archivo de la Plantilla')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documento.categoriadocumento', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Plantilla Documental',
                'verbose_name_plural': 'Plantillas Documentales',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
