# Generated by Django 4.2.23 on 2025-08-04 12:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriadocumento',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Color de la Categoría'),
        ),
    ]
