# Generated by Django 4.2.23 on 2025-07-15 06:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaFestivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo del festivo')),
            ],
            options={
                'verbose_name': 'Día Festivo',
                'verbose_name_plural': 'Días Festivos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='AsuntosParticulares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('fecha_modificacion', models.DateField(auto_now=True, verbose_name='Última Modificación')),
                ('telefono', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe tener 9 dígitos y empezar por 6 o 7.', regex='^[67]\\d{8}$')], verbose_name='Número de Teléfono')),
                ('relacion_juridica', models.CharField(choices=[('carrera', 'Personal funcionario de carrera'), ('practicas', 'Personal funcionario en prácticas'), ('interino', 'Personal funcionario interino')], max_length=10, verbose_name='Relación Jurídica')),
                ('jornada', models.CharField(choices=[('completa', 'Completa'), ('parcial', 'Parcial')], max_length=10, verbose_name='Jornada')),
                ('hace_sustitucion', models.BooleanField(default=False, verbose_name='¿Hace sustitución?')),
                ('retribuido', models.BooleanField(default=False, verbose_name='¿Retribuido?')),
                ('dia_solicitado', models.DateField(verbose_name='Día Solicitado')),
                ('es_causa_sobrevenida', models.BooleanField(default=False, verbose_name='¿Causa sobrevenida?')),
                ('justificacion_causa_sobrevenida', models.TextField(blank=True, null=True, verbose_name='Justificación de la causa sobrevenida')),
                ('horas_afectadas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Número de horas de docencia directa y guardias afectadas')),
                ('dias_permiso_solicitados_centro', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Número de días de permisos solicitados en el centro')),
                ('consentimiento_grabacion', models.BooleanField(default=False, verbose_name='Entiendo que mi identidad, así como la fecha y hora de registro de la petición quedan grabadas automáticamente en el momento del envío del formulario.')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asuntos_particulares', to=settings.AUTH_USER_MODEL, verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Asunto Particular',
                'verbose_name_plural': 'Asuntos Particulares',
            },
        ),
    ]
