# Generated by Django 4.2.23 on 2025-07-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuntosParticulares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuntosparticulares',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10, verbose_name='Estado de la Solicitud'),
        ),
    ]
