# Generated by Django 4.2.23 on 2025-07-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuntosParticulares', '0002_asuntosparticulares_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='asuntosparticulares',
            name='turno_solicitado',
            field=models.CharField(choices=[('diurno', 'Diurno'), ('vespertino', 'Vespertino')], default='diurno', max_length=10, verbose_name='Turno Solicitado'),
        ),
    ]
