# Generated by Django 4.2.23 on 2025-07-25 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuntosParticulares', '0003_asuntosparticulares_turno_solicitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuntosparticulares',
            name='consentimiento_grabacion',
            field=models.BooleanField(default=False, verbose_name='Entiendo que los datos del formulario, así como mi identidad, la fecha y hora de registro de la petición quedan grabadas automáticamente en el momento del envío del formulario.'),
        ),
        migrations.AlterField(
            model_name='asuntosparticulares',
            name='dias_permiso_solicitados_centro',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Núm de días de permisos solicitados en el centro'),
        ),
        migrations.AlterField(
            model_name='asuntosparticulares',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Modificación'),
        ),
        migrations.AlterField(
            model_name='asuntosparticulares',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud'),
        ),
        migrations.AlterField(
            model_name='asuntosparticulares',
            name='hace_sustitucion',
            field=models.BooleanField(default=False, verbose_name='¿Estás haciendo una sustitución?'),
        ),
        migrations.AlterField(
            model_name='asuntosparticulares',
            name='horas_afectadas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Núm de horas de docencia directa y guardias afectadas'),
        ),
        migrations.AlterField(
            model_name='asuntosparticulares',
            name='retribuido',
            field=models.BooleanField(default=False, verbose_name='Estoy solicitando un día de permiso no retribuido'),
        ),
    ]
