# Generated by Django 4.2.23 on 2025-08-01 10:41

import asuntosParticulares.models.asuntosParticulares
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuntosParticulares', '0004_alter_asuntosparticulares_consentimiento_grabacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asuntosparticulares',
            options={'ordering': ['-dia_solicitado', 'pk'], 'verbose_name': 'Asunto Particular', 'verbose_name_plural': 'Asuntos Particulares'},
        ),
        migrations.AddField(
            model_name='asuntosparticulares',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Sube un documento PDF que justifique tu solicitud sobrevenida.', null=True, upload_to=asuntosParticulares.models.asuntosParticulares.ruta_archivo, validators=[asuntosParticulares.models.asuntosParticulares.validar_solo_pdf], verbose_name='Archivo Adjunto'),
        ),
    ]
