# Generated by Django 4.2.23 on 2025-08-05 12:46

import asuntosParticulares.models.asuntosParticulares
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuntosParticulares', '0005_alter_asuntosparticulares_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asuntosparticulares',
            name='archivo_adjunto',
            field=models.FileField(blank=True, help_text='Sube un documento PDF que justifique tu solicitud sobrevenida.', null=True, upload_to=asuntosParticulares.models.asuntosParticulares.ruta_archivo, validators=[asuntosParticulares.models.asuntosParticulares.validar_solo_pdf], verbose_name='Documento Justificativo en PDF'),
        ),
    ]
